#! /bin/bash

# Funcoes ------------------------------------------------------------------------------------------

Help() {
    # Mostra o help
   echo "Programa para execucao do aplicativo eolicas-newave."
   echo
   echo "Uso: eolicas-newave [arq_conf] deck"
   echo ""
   echo "argumentos:"
   echo ""
   echo "    arq_conf: opcional, indicando um arquivo de configuracao .json para parte de dados"
   echo "    dec     : obrigatorio, indicando um deck de newave zipado para manipular"
   echo ""
}

# Execucao -----------------------------------------------------------------------------------------

VERSION="1.0.0"
DATE="29/07/2022"

USERINSTALLDIR=/usr/lib
INSTALLDIR=${USERINSTALLDIR}/eolicas-newave

if [ $# -eq 2 ]; then
    echo ""
    echo "eolicas-newave"
    echo "Gerência de Metodologias e Modelos Energéticos - PEM / ONS"
    echo "Versão ${VERSION} - ${DATE}"
    echo ""

    eolicas-newave-dados $1
    eolicas-newave-deck geradeck $2

elif [ $# -eq 1 ]; then
    echo ""
    echo "eolicas-newave"
    echo "Gerência de Metodologias e Modelos Energéticos - PEM / ONS"
    echo "Versão ${VERSION} - ${DATE}"
    echo ""

    eolicas-newave-dados
    eolicas-newave-deck geradeck $1
else
    echo "ERRO: forneca pelo menos um arquivo de deck compactado"
    echo ""
    echo "------------------------------------------------------"
    echo ""
    Help
    exit 1
fi
