#! /bin/bash

# Funcoes ------------------------------------------------------------------------------------------

Help() {
    # Mostra o help
   echo "Programa para execucao do aplicativo eolicas-newave."
   echo
   echo "Uso: eolicas-newave comando [-h] [-a=arquivo_conf_dados.jsonc] [-d=deck_newave.zip]"
   echo ""
   echo "comandos:"
   echo "    dados        executa a clisterizacao, estimacao de ftm e adicao de usinas"
   echo "    deck         manipula um deck de newave com as informacoes de eolicas pertinentes"
   echo "    full         executa as duas partes concatenadas"
   echo ""
   echo "opcoes:"
   echo "    a     caminho ate um arquivo de configuracao para a parte -dados do aplicativo"
   echo "    d     caminho ate um deck compactado para manipular"
   echo "    h     Imprime esta pagina de ajuda"
   echo ""
}

RUN_DADOS() {
    ARQCONF=$1
    eolicas-newave-dados "$ARQCONF"
}

RUN_DECK() {
    DECK=$1
    eolicas-newave-deck "$DECK"
}

RUN_FULL() {
    ARQCONF=$1
    DECK=$2

    eolicas-newave-dados "$ARQCONF"
    eolicas-newave-deck geradeck "$DECK"
}

# Execucao -----------------------------------------------------------------------------------------

VERSION="1.0.0"
DATE="29/07/2022"

USERINSTALLDIR=/usr/lib
INSTALLDIR=${USERINSTALLDIR}/eolicas-newave

while getopts "a:d:" arg; do
    case "${arg}" in
        a) ARQCONF=${OPTARG}
        ;;
        d) DECK=${OPTARG}
        ;;
    esac
done

if [ "$1" == "dados" ]; then
    RUN_DADOS ARQCONF
elif [ "$1" == "deck" ]; then
    RUN_DECK DECK
elif [ "$1" == "full" ]; then
    RUN_FULL ARQCONF DECK
else
    echo ""
    echo "ERRO: nenhum comando fornecido"
    echo ""
    echo "----------------------------------------"
    echo ""
    Help
    exit 1
fi

echo ""
echo "eolicas-newave"
echo "Gerência de Metodologias e Modelos Energéticos - PEM / ONS"
echo "Versão ${VERSION} - ${DATE}"
echo ""